modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="mail_addon"
version="1.0.2"
displayName="Mail Addon"
credits=""
displayURL="https://github.com/Aosiho/MailAddon"
logoFile="logo.png"
authors="Aosiho"

[[dependencies.mail_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"




